# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 969824fdd59ac7458e7fdecd13999d5c52f1ab3cb35694c3da8ca447b4e92197412a0ac9f738e5ef7a88365c60662e046d762e3414d781ea2d839785925a82ad

test:
  secret_key_base: 42062e12d272fd276f196f121dea57e8b786c3ddb3ef60f0703d0c17c86086780cd3083f4a86544b286722a0878701eb9968de9455592392335df2982c733924

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
